server:
  port: 8025
spring:
  application:
    name: light-user
  profiles:
    active: dev
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'