spring:
  datasource:
    username: root
    password: xhnya@1216
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.35.8.166:63306/light_user?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=utf-8
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

##设置feign客户端超时时间(OpenFeign默认支持ribbon)
#ribbon:
#  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
#  ReadTimeout: 5000
#  #指的是建立连接后从服务器读取到可用资源所用的时间
#  ConnectTimeout: 5000

#logging:
#  level:
#    # feign日志以什么级别监控哪个接口
#    com.xhn.light.community.client.GameFeignService: debug

## 用于服务降级 在注解@FeignClient中添加fallbackFactory属性值
#feign:
#  hystrix:
#    enabled: true #在Feign中开启Hystrix