server:
  port: 8025
spring:
  application:
    name: light-user
  profiles:
    active: dev
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      #采样率值介于 0 到 1 之间，1 则表示全部采集
      probability: 1
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'