spring:
  cloud:
    gateway:
      routes:
        - id: light_admin
          uri: lb://light-admin
          predicates:
            - Path=/api/admin/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: user_admin
          uri: lb://exercise-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
