spring:
  cloud:
    gateway:
      routes:
        - id: light_admin
          uri: lb://light-admin
          predicates:
            - Path=/api/admin/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: light_cloud
          uri: lb://light-cloud
          predicates:
            - Path=/api/cloud/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: light_game
          uri: lb://light-game
          predicates:
            - Path=/api/game/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}


        - id: user_admin
          uri: lb://exercise-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
