spring:
  cloud:
    gateway:
      routes:
        - id: admin_admin
          uri: lb://light-admin
          predicates:
            - Path=/api/admin/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_cloud
          uri: lb://light-cloud
          predicates:
            - Path=/api/cloud/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_game
          uri: lb://light-game
          predicates:
            - Path=/api/game/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_community
          uri: lb://light-community
          predicates:
            - Path=/api/community/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_user
          uri: lb://light-user
          predicates:
            - Path=/api/user/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: light_user
          uri: lb://light-user
          predicates:
            - Path=/light/user/**
          filters:
            - RewritePath=/light/(?<segment>.*),/$\{segment}

        - id: light_admin
          uri: lb://light-admin
          predicates:
            - Path=/light/admin/**
          filters:
            - RewritePath=/light/(?<segment>.*),/$\{segment}

        - id: light_game
          uri: lb://light-game
          predicates:
            - Path=/light/game/**
          filters:
            - RewritePath=/light/(?<segment>.*),/$\{segment}

        - id: light_community
          uri: lb://light-community
          predicates:
            - Path=/light/community/**
          filters:
            - RewritePath=/light/(?<segment>.*),/$\{segment}

        - id: light_auth
          uri: lb://light-auth
          predicates:
            - Path=/light/auth/**
          filters:
            - RewritePath=/light/(?<segment>.*),/$\{segment}

