spring:
  profiles:
    active: dev
  application:
    name: light-cloud
  rabbitmq:
    host: 101.35.8.166
    port: 5673
    username: guest
    password: guest
  cloud:
    #sentinel
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
server:
  port: 8010
management:
  endpoints:
    web:
      exposure:
        include: '*'